install: gradle wrapper --gradle-version 3.5
language: java
php:
- openjdk8
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_544ddaa54e49_key -iv $encrypted_544ddaa54e49_iv in laplace.enc -out ~\/.ssh/laplace -d
before_script:
- sudo apt-get -qq update
- sudo apt-get -y install unzip
- sudo apt-get -y install curl
- curl -s "https://get.sdkman.io" | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- sdk install grails
- echo -e "Host beatbox.co.ke\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- grails test-app
- cd $TRAVIS_BUILD_DIR
- chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
   branch: master
  skip_cleanup: true
notifications:
  email:
    recipients:
      - bdhobare@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
