language: php
php:
- 7.1
addons:
  postgresql: 9.6
services:
- postgresql
before_script:
- cp .env.travis .env
- sudo apt-get -qq update
- sudo apt-get install -y postgresql-9.6-postgis-2.4
- psql -c 'create database iziaddress_test;' -U postgres
- psql -U postgres -d iziaddress_test -c 'create extension postgis'
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- echo -e "Host beatbox.co.ke\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- vendor/bin/phpunit
- cd $TRAVIS_BUILD_DIR
- chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
   branch: master
  skip_cleanup: true
#after_success: "./.travis/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_75310dc6db60_key -iv $encrypted_75310dc6db60_iv
  -in travis.enc -out travis -d
notifications:
  email:
    recipients:
      - bdhobare@gmail.com
      - miles@iziaddress.com
    on_success: change # default: change
    on_failure: change # default: always
