language: java
jdk:
- openjdk7
- oraclejdk7
before_install:
- openssl aes-256-cbc -K $encrypted_544ddaa54e49_key -iv $encrypted_544ddaa54e49_iv
- in laplace.enc -out ~\/.ssh/laplace -d
- sudo add-apt-repository -y ppa:groovy-dev/grails
- sudo apt-get update
- sudo apt-get -y install unzip
- sudo apt-get -y install curl
- curl -s "https://get.sdkman.io" | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- sdk install grails
before_script:
- echo -e "Host beatbox.co.ke\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- grails test-app
- cd $TRAVIS_BUILD_DIR
- chmod +x ./deploy.sh
deploy:
 provider: script
 script: ./deploy.sh
  on:
   branch: master
  skip_cleanup: true